language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t neilmassey/docker-react -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true neilmassey/docker-react npm run test
